// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ViaReservaERP.Data;

#nullable disable

namespace ViaReservaERP.Migrations
{
    [DbContext(typeof(ViaReservaDbContext))]
    [Migration("20260507020500_AddEnterpriseInquiries")]
    partial class AddEnterpriseInquiries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
